export const companies = [
  "/images/companies/c1.webp",
  "/images/companies/c2.webp",
  "/images/companies/c3.webp",
  "/images/companies/c4.webp",
  "/images/companies/c5.webp",
  "/images/companies/c6.webp",
  "/images/companies/c7.webp",
  "/images/companies/c8.webp",
  "/images/companies/c9.webp",
  "/images/companies/c10.webp",
  "/images/companies/c11.webp",
  "/images/companies/c12.webp",
  "/images/companies/c13.webp",
  "/images/companies/c14.webp",
  "/images/companies/c15.webp",
];
